Supply Vault
morpho-org/morpho-aave-v3 pull request #783
Opened 2023-04-20 23:58 UTC by pakim249CAL

# Pull Request

## Issue(s) fixed

This pull request:

fixes 
* #782

2023-05-03 07:16 UTC, Rubilmax requested changes

2023-05-03 07:16 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
> +        _recipient = newRecipient;
Shouldn't it be set at initialization then?

2023-05-03 08:56 UTC, MerlinEgalite requested changes

2023-05-03 14:19 UTC, pakim249CAL commented on src/extensions/SupplyVault.sol
> +        _recipient = newRecipient;
Not sure which commit you are reviewing, but this has been moved to initialization already.

2023-05-03 16:27 UTC, MerlinEgalite requested changes

2023-05-03 16:27 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
`__SupplyVault_init_unchained` should revert if `newUnderlying` is zero IMO

2023-05-03 16:27 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
>              uint256 amount = ERC20(tokens[i]).balanceOf(address(this));
tokens[i] could be put in the stack with a `token` variable

2023-05-03 16:27 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
Why not setting maxIterations to a `uint96` instead I think it would be better as it would fill the entire slot

2023-05-03 17:49 UTC, pakim249CAL commented on src/extensions/SupplyVault.sol
>              uint256 amount = ERC20(tokens[i]).balanceOf(address(this));
I feel like optimizing skim is unnecessary.

2023-05-03 17:50 UTC, pakim249CAL commented on src/extensions/SupplyVault.sol
Why would it be a benefit to fill the entire slot?

2023-05-03 18:01 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
because there's only one mask to apply instead of 2 (on each side of the uint8)

2023-05-04 07:44 UTC, Rubilmax approved these changes

2023-05-04 07:44 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
The operation to retrieve a `uint8` in the middle of a `bytes32` is just: `word & 0...01111111100...0` so there's still a unique mask applied?

EDIT: ok I get it, it's not a matter of 2 masks but rather 2 operations. After having masked the complement of the bytes, you also need to shift them so that data starts at the lowest bit: `word & 0...01111111100...0 >> 88`

2023-05-04 07:45 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
You're it's a shift that is applied thx!

2023-05-04 07:47 UTC, MerlinEgalite requested changes

2023-05-04 07:47 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +    address internal immutable _UNDERLYING; // The underlying market to supply to through this vault.
Why are we going back to immutable? I don't get it

2023-05-04 14:55 UTC, pakim249CAL commented on src/extensions/SupplyVault.sol
> +    ///      The vault is not intended to hold any ERC20 tokens between calls.
This is a continuation of the previous line though. Is this not the correct way to wrap lines in comments?

2023-05-04 15:28 UTC, Tristan22400 commented on src/extensions/SupplyVault.sol
> +    ///      The vault is not intended to hold any ERC20 tokens between calls.
I don't know this seems strange to me.

2023-05-04 15:51 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +    address internal immutable _UNDERLYING; // The underlying market to supply to through this vault.
Yes please in doubt I would prefer that we keep it as a storage variable

2023-05-05 07:27 UTC, MerlinEgalite submitted a review, later dismissed

2023-05-05 07:27 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +        }
can we just inline it?

2023-05-05 08:35 UTC, Tristan22400 submitted a review, later dismissed

2023-05-05 12:30 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
> +        }
Forge fmt prevents inlining this

2023-05-05 12:30 UTC, Rubilmax submitted a review, later dismissed

2023-05-05 14:57 UTC, makcandrov approved these changes

2023-05-05 14:57 UTC, makcandrov commented on src/extensions/SupplyVault.sol
> +import {Types} from "src/libraries/Types.sol";
```suggestion
```

2023-05-05 14:57 UTC, makcandrov commented on src/extensions/SupplyVault.sol
> +    using WadRayMath for uint256;
```suggestion
```

2023-05-05 16:05 UTC, MerlinEgalite submitted a review, later dismissed

2023-05-09 06:35 UTC, Rubilmax submitted a review, later dismissed

2023-05-09 07:34 UTC, makcandrov approved these changes

2023-05-09 09:06 UTC, Tristan22400 commented
A few comments, I would like to add that I cannot add directly. 
1°) https://github.com/morpho-org/morpho-aave-v3/blob/3844e13730d062e191f8535187feb4cef88a59d6/test/extensions/vaults/TestIntegrationSupplyVault.sol#L123
It does not correspond to the right error in my opinion as the promoter did not supply. You should have the ERC20 insuffisant allowance according to me. 
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/dd8ca8adc47624c5c5e2f4d412f5f421951dcc25/contracts/token/ERC20/ERC20Upgradeable.sol#LL332C13-L332C13

2°) In the withdraw test on the vault, you should have an assertion to check if the amount withdraw correspond to the amount deposit by checking that the balanceBefore should be almost equal to the balance after of the address which deposited. 
https://github.com/morpho-org/morpho-aave-v3/blob/3844e13730d062e191f8535187feb4cef88a59d6/test/extensions/vaults/TestIntegrationSupplyVault.sol#L70-L107

2023-05-09 09:14 UTC, Tristan22400 commented on test/extensions/vaults/TestIntegrationVaultsUpgradeable.sol
> +        vm.prank(address(user));
user address can fuzzed

2023-05-10 08:32 UTC, MerlinEgalite submitted a review, later dismissed

2023-05-10 08:44 UTC, Tristan22400 approved these changes

2023-05-10 09:12 UTC, Rubilmax approved these changes

2023-05-10 09:12 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
I don't get this change: why is it better to flatten the initialization chain?
I like a software better when it's split into small, understandable and isolated functions. I may have missed a discussion though.

2023-05-10 09:15 UTC, Rubilmax requested changes
Wait for `dev` to be synced. Also, the base branch should be `dev`?

EDIT: I get it. `[fix/repay-eth-test-fail](https://github.com/morpho-org/morpho-aave-v3/tree/fix/repay-eth-test-fail)` is redundant with what was already merged on `main`

2023-05-10 09:15 UTC, Rubilmax commented on test/helpers/IntegrationTest.sol
> +        vm.assume(onBehalf != address(proxyAdmin));
This was fixed another way on `main` but `dev` is outdated. See https://github.com/morpho-org/morpho-aave-v3/pull/826

2023-05-10 09:50 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
To me this function is useless since the contract has not been designed to be reusable. Discussed here: https://github.com/morpho-org/morpho-aave-v3/pull/820

If it's a blocker you can roll back changes if you want

2023-05-10 09:55 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
It's not a blocker, it's just bad software design. I really see the benefits of small, re-usable, isolated functions since Morpho-AaveV3 where we've encountered many times that we should have isolated some behaviors to dedicated functions (e.g. `trueP2PSupply`, `trueP2PBorrow`, and there are many others). The same applies here: better to have software design protect us from bugs, at the cost of readability (the reader must go through layers of code).
I know this opinion is not shared among the team.

2023-05-10 10:42 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
I agree with you for the sofware design. However, the code is not reused so there's only one place that you need to apply the changes and the code is not so long. This is exactly what we have in the `initialize` function in `morpho-v1` or `morpho-aave-v3`:

https://github.com/morpho-org/morpho-aave-v3/blob/d1cc13a6c570222db24a472985908d0325bf70f0/src/Morpho.sol#L38-L56

Adding this function just leavs open the question for the auditor wether this contract will inherited or not.

2023-05-10 11:50 UTC, pakim249CAL commented on test/helpers/IntegrationTest.sol
> +        vm.assume(onBehalf != address(proxyAdmin));
I will revert the commits.

2023-05-10 13:09 UTC, Rubilmax commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
> Adding this function just leavs open the question for the auditor wether this contract will inherited or not.

Indeed! What's the downside of it? Raising questions seems to be an advantage.

2023-05-10 13:28 UTC, MerlinEgalite commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
Not if it's unnecessary or there's no intention for a specific usage. Less ambiguity => less questions => more time on more important things

2023-05-10 14:13 UTC, MerlinEgalite approved these changes

2023-05-10 16:10 UTC, pakim249CAL commented on src/extensions/SupplyVault.sol
> +        __ERC4626UpgradeableSafe_init_unchained(initialDeposit);
Overall I agree with @Rubilmax, but practically speaking I don't think there's much of an issue here since SupplyVault is not going to be inherited. Therefore any lack of componentization has really no consequence at all, so I consider this issue in this case to be a style issue.

2023-05-10 16:38 UTC, MerlinEgalite submitted a review, later dismissed

2023-05-11 08:04 UTC, Tristan22400 approved these changes

2023-05-11 08:37 UTC, Rubilmax approved these changes

2023-05-11 09:15 UTC, MerlinEgalite approved these changes

2023-05-11 09:25 UTC, makcandrov approved these changes

2023-05-11 09:45 UTC, merged