Add min in wrap/unwrap/supply
morpho-org/morpho-aave-v3 pull request #845
Opened 2023-05-30 14:18 UTC by MerlinEgalite

# Pull Request

## Issue(s) fixed

This pull request:

- fixes #843

2023-05-30 14:44 UTC, Rubilmax submitted a review, later dismissed

2023-05-31 06:25 UTC, julien-devatom reviewed
IMO you should revert with AmountIsZero() if the min is zero, like that: 

```solidity
  function _unwrapStEth(bytes calldata data) internal {
        (uint256 amount, address receiver) = abi.decode(data, (uint256, address));

        amount = Math.min(amount, ERC20(_WST_ETH).balanceOf(address(this)));

        if (amount == 0) revert AmountIsZero();
        if (receiver == address(this)) revert TransferToSelf();


        uint256 unwrapped = IWSTETH(_WST_ETH).unwrap(amount);

        ERC20(_ST_ETH).safeTransfer(receiver, unwrapped);
    }
```

2023-05-31 06:25 UTC, julien-devatom commented on test/integration/TestIntegrationBulkerGateway.sol
> +        assertApproxEqAbs(ERC20(stETH).balanceOf(address(bulker)), 0, 1, "bulker balance");
Can you add a comment about why its an approximation at 1wei now?

2023-05-31 08:22 UTC, Tristan22400 requested changes
I am wondering why you did not add the same thing to the repay function. 
https://github.com/morpho-org/morpho-aave-v3/blob/f3aebab4881242730994e7025cf6bd51b31c0c55/src/extensions/BulkerGateway.sol#L197

2023-05-31 08:26 UTC, Tristan22400 commented on src/extensions/BulkerGateway.sol
> +        IWSTETH(_WST_ETH).wrap(Math.min(amount, ERC20(_ST_ETH).balanceOf(address(this))));
maybe it makes more sense to check if the amount is zero after taking the minimum on the function. What do you think ?

2023-05-31 08:45 UTC, MerlinEgalite commented
> I am wondering why you did not add the same thing to the repay function.
> 
> https://github.com/morpho-org/morpho-aave-v3/blob/f3aebab4881242730994e7025cf6bd51b31c0c55/src/extensions/BulkerGateway.sol#L197

Because it takes the max of (amount, debt) so I would expect pass an infinite amount instead of a specific amount. I can change this though, @julien-devatom wdyt?

2023-05-31 13:07 UTC, makcandrov commented on src/extensions/BulkerGateway.sol
> +        IWSTETH(_WST_ETH).wrap(Math.min(amount, ERC20(_ST_ETH).balanceOf(address(this))));
I think it's better to take the minimum before the null check (here and everywhere else too)

2023-05-31 16:02 UTC, Tristan22400 submitted a review, later dismissed

2023-06-01 01:20 UTC, pakim249CAL approved these changes

2023-06-01 05:44 UTC, julien-devatom approved these changes
🚀 🔥 LGTM 🔥 🚀

2023-06-01 07:15 UTC, Rubilmax approved these changes

2023-06-01 07:34 UTC, merged