Fix flashloan inflation hack
morpho-org/morpho-aave-v3 pull request #849
Opened 2023-06-05 07:39 UTC by Rubilmax

This branch contains changes applied through the latest upgrade of Morpho-AaveV3 contracts

2023-06-05 08:41 UTC, MerlinEgalite submitted a review, later dismissed

2023-06-05 08:47 UTC, Tristan22400 submitted a review, later dismissed

2023-06-05 15:12 UTC, pakim249CAL submitted a review, later dismissed

2023-06-06 09:01 UTC, MathisGD commented on test/integration/TestIntegrationWithdrawCollateral.sol
A test that the p2pIndexes are correctly updated could be added (similar to what I have done in ma2 and mc).

2023-06-06 16:36 UTC, MerlinEgalite submitted a review, later dismissed

2023-06-07 08:01 UTC, MathisGD submitted a review, later dismissed

2023-06-07 08:51 UTC, Tristan22400 requested changes

2023-06-07 08:51 UTC, Tristan22400 commented on test/integration/TestIntegrationMorphoGetters.sol
> +        TestMarket storage market = testMarkets[_randomCollateral(seed)];
Why are we taking only collateral asset? I suggest to use all suppliable assets?

2023-06-07 08:51 UTC, Tristan22400 commented on test/integration/TestIntegrationMorphoGetters.sol
> +        TestMarket storage market = testMarkets[_randomCollateral(seed)];
same here

2023-06-07 08:51 UTC, Tristan22400 commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +    function testShouldNotWithdrawMoreCollateralThanSuppliedWhenFlashLoanInflates(uint256 seed) public {
change the name

2023-06-07 08:51 UTC, Tristan22400 commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +        TestMarket storage market = testMarkets[_randomCollateral(seed)];
same here

2023-06-07 09:20 UTC, Rubilmax commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +        TestMarket storage market = testMarkets[_randomCollateral(seed)];
This test specifically is about collateral assets!

2023-06-07 09:20 UTC, Rubilmax commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +    function testShouldNotWithdrawMoreCollateralThanSuppliedWhenFlashLoanInflates(uint256 seed) public {
What for?

2023-06-07 09:27 UTC, Tristan22400 commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +        TestMarket storage market = testMarkets[_randomCollateral(seed)];
ok understood but we should do the same for suppliable assets so.

2023-06-07 09:28 UTC, Tristan22400 commented on test/integration/TestIntegrationWithdrawCollateral.sol
> +    function testShouldNotWithdrawMoreCollateralThanSuppliedWhenFlashLoanInflates(uint256 seed) public {
it was about removing collateral word but it is fine after your comment.

2023-06-07 15:07 UTC, pakim249CAL approved these changes

2023-06-07 17:08 UTC, QGarchery approved these changes

2023-06-07 17:22 UTC, MerlinEgalite approved these changes

2023-06-08 07:33 UTC, MathisGD approved these changes

2023-06-08 07:35 UTC, merged